name: NuGet Package

on:
  release:
    types: [published]

jobs:
  build:
    name: Build + Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
      - run: dotnet pack
      - name: Publish to NuGet
        run: dotnet nuget push Gorse.NET/bin/Debug/Gorse.NET.*.nupkg --api-key ${NUGET_API_KEY} --source https://api.nuget.org/v3/index.json
        env:
          NUGET_API_KEY: "${{secrets.NUGET_API_KEY}}"
